app/uk/gov/hmrc/plasticpackagingtaxreturns/audit/ChangeSubscriptionEvent.scala

PPTP-1010 Added nrs details to change subscription event

---

app/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/models/eis/subscription/BusinessCorrespondenceDetails.scala

PPTP-1225 Addressline2 trimmed if populated with blank space.

---

app/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/EISConnector.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/SubscriptionsConnector.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/services/nonRepudiation/NonRepudiationService.scala

Improved logging

---

README.md
app/uk/gov/hmrc/plasticpackagingtaxreturns/config/AppConfig.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/ExportCreditBalanceConnector.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/models/eis/exportcreditbalance/ExportCreditBalanceDisplayResponse.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/ExportCreditBalanceController.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/query/QueryStringParams.scala
build.sbt
conf/app.routes
test/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/ExportCreditBalanceConnectorSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/SubscriptionsConnectorSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/base/unit/MockConnectors.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/controllers/ExportCreditBalanceControllerSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/models/EISError.scala

PPTP-1460 - integrate with export credit balance display API

---

app/uk/gov/hmrc/plasticpackagingtaxreturns/config/AppConfig.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/ReturnsConnector.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/models/eis/returns/Return.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/ReturnsSubmissionController.scala
conf/app.routes
test/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/ReturnsConnectorISpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/base/unit/MockConnectors.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/builders/ReturnsSubmissionResponseBuilder.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/controllers/ReturnsSubmissionControllerSpec.scala

PPTP-1128 - Returns Display

---

app/uk/gov/hmrc/plasticpackagingtaxreturns/config/AppConfig.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/DESConnector.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/ObligationDataConnector.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/models/des/enterprise/ObligationDataResponse.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/ObligationDataController.scala
conf/app.routes
conf/application.conf
test/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/ObligationDataConnectorSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/ReturnsConnectorISpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/base/it/ConnectorISpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/base/unit/MockConnectors.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/config/AppConfigSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/controllers/ObligationDataControllerSpec.scala

PPTP-450 Integrate with API - Get Obligation Data

---

README.md
app/uk/gov/hmrc/plasticpackagingtaxreturns/config/AppConfig.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/DateFormat.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/ExportCreditBalanceConnector.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/FinancialDataConnector.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/ObligationDataConnector.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/QueryParams.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/models/des/enterprise/FinancialDataResponse.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/FinancialDataController.scala
conf/app.routes
test/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/ExportCreditBalanceConnectorISpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/FinancialDataConnectorISpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/ObligationDataConnectorISpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/QueryParamsSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/base/unit/MockConnectors.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/controllers/FinancialDataControllerSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/models/EnterpriseTestData.scala

Integrate with API #1166 - Query Financial Transactions
Stub PR - https://github.com/hmrc/plastic-packaging-tax-stub/pull/47

PPTP-544 - get financial data

---

project/AppDependencies.scala
project/plugins.sbt

BAU - update dependencies

---

it/PPTObligationsISpec.scala

Workaround - Paul's PR blocked because of earlier unverified commits

Adding integration test to validate obligationDetails in response

---

conf/app.routes
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/controllers/ReturnsControllerSpec.scala

updating FE path
Dependencies:
- https://github.com/hmrc/app-config-base/pull/6843
- https://github.com/hmrc/plastic-packaging-tax-returns-frontend/pull/110

PPTP-1755 - updating FE path

---

app/uk/gov/hmrc/plasticpackagingtaxreturns/models/TaxReturn.scala

PPTP-1647 Imported plastic

---

app/uk/gov/hmrc/plasticpackagingtaxreturns/models/TaxReturn.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/models/TaxReturnRequest.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/builders/TaxReturnBuilder.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/builders/TaxReturnRequestBuilder.scala

FE PR: https://github.com/hmrc/plastic-packaging-tax-returns-frontend/pull/107

PPTP-1646 : Revised Manufactured Plastic Packaging Return Questions

---

app/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/models/eis/returns/ReturnsSubmissionRequest.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/models/ReturnType.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/models/TaxReturn.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/ReturnsConnectorISpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/models/eis/returns/ReturnsSubmissionRequestSpec.scala

PPTP-1775 Create returns BE

---

conf/app.routes
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/controllers/ReturnsControllerSpec.scala

This reverts commit fc5547a4ac5a6fab5280779e8397042a4ccb897c.

Revert "PPTP - updating FE path"

---

app/uk/gov/hmrc/plasticpackagingtaxreturns/config/AppConfig.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/FinancialDataConnector.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/models/des/enterprise/FinancialDataResponse.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/FinancialDataController.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/PPTFinancialsController.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/PPTObligationsController.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/models/PPTFinancials.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/services/FinancialDataService.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/services/PPTFinancialsService.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/services/PPTObligationsService.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/services/package.scala
conf/app.routes
conf/prod.routes
it/PPTFinancialsItSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/FinancialDataConnectorISpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/base/unit/MockConnectors.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/controllers/PPTFinancialsControllerSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/controllers/PPTObligationsControllerSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/models/EnterpriseTestData.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/services/FinancialDataServiceSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/services/PPTFinancialsServiceSpec.scala

API for fincails used by PPT and BTA to render Tile info

PPTP-1459 | API to surface financial data

---

app/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/ReturnsSubmissionController.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/repositories/TaxReturnRepository.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/controllers/ReturnsSubmissionControllerSpec.scala

delete return on amend success

---

app/uk/gov/hmrc/plasticpackagingtaxreturns/config/Module.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/CacheController.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/models/cache/UserAnswers.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/repositories/SessionRepository.scala
build.sbt
conf/app.routes
conf/application.conf
it/repositories/SessionRepositorySpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/base/unit/MockReturnsRepository.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/controllers/CacheControllerSpec.scala

Bring user answers cache into the back end

---

app/uk/gov/hmrc/plasticpackagingtaxreturns/services/PPTFinancialsService.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/services/PPTFinancialsServiceSpec.scala

debit now total

---

app/uk/gov/hmrc/plasticpackagingtaxreturns/audit/Auditor.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/audit/SubmitReturnEvent.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/models/eis/returns/NrsReturnOrAmendSubmission.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/models/eis/returns/Return.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/models/eis/returns/ReturnsSubmissionRequest.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/ReturnsSubmissionController.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/models/TaxReturn.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/builders/ReturnsSubmissionResponseBuilder.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/controllers/ReturnsSubmissionControllerSpec.scala

Submit EIS payload to NRS.
Audit payload out NRS outcome.

PPTP-1435 | NRS submission for returns and amends

---

app/uk/gov/hmrc/plasticpackagingtaxreturns/config/AppConfig.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/ObligationsDataConnector.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/models/des/enterprise/ObligationDataResponse.scala
build.sbt
test/uk/gov/hmrc/plasticpackagingtaxreturns/models/PPTObligationDetailsSpec.scala

adjustDates

---

app/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/CacheController.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/ReturnsSubmissionController.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/actions/AuthenticatorImpl.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/base/AuthTestSupport.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/controllers/CacheControllerSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/controllers/ReturnsSubmissionControllerSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/models/SignedInUser.scala

PPTP-2258 | Implement cache Id

---

build.sbt

PPT Returns BE Major version bump to 1

---

it/PPTObligationsISpec.scala

stop obligation from being due

---

app/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/ReturnsSubmissionController.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/builders/ReturnsSubmissionResponseBuilder.scala

Fix for date parse issue

---

app/uk/gov/hmrc/plasticpackagingtaxreturns/services/PPTCalculationService.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/util/LogCapturing.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/services/PPTCalculationServiceSpec.scala

PPTP-2433: Added an info log for return not submittable for kibana dashboard. Will create a chart based on this log.

PPTP-2433: Added an info log for return not submittable for kibana

---

app/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/SubscriptionsConnector.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/SubscriptionsConnectorSpec.scala

PPTP-2496 | clense json of illegal characters

---

app/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/CalculationsController.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/ReturnsController.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/models/cache/gettables/amends/ReturnDisplayApiGettable.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/models/returns/ReturnValues.scala
conf/app.routes
it/PPTObligationsISpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/controllers/ReturnsControllerSpec.scala

- Amends builds from UserAnswers pulling original value if new amend value isnt present 
- SubmissionID extracted from Original to save frontend form doing it.
- Api end point added for calculations for amends to use

PPTP-2510 | backend changes to support amends submission and calculation

---

app/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/CalculationsController.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/models/calculations/Calculations.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/models/returns/ReturnValues.scala

Amends calc

---

app/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/models/des/enterprise/FinancialDataResponse.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/services/PPTFinancialsService.scala
it/PPTFinancialsItSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/models/EnterpriseTestData.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/models/ReturnsTestData.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/services/PPTFinancialsServiceSpec.scala

For https://jira.tools.tax.service.gov.uk/browse/PPTP-2152, don't allow an amend with 3 days of direct debit collection

Check for DD flag (and log) when calling Financials api

---

app/uk/gov/hmrc/plasticpackagingtaxreturns/services/AvailableCreditService.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/services/AvailableCreditServiceSpec.scala

Stop calls to EIS when no credit is being claimed

---

app/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/PPTObligationsController.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/controllers/PPTObligationsControllerSpec.scala

Reverts hmrc/plastic-packaging-tax-returns#112
Remove the probe tests complete can now see succseful calls in production

Revert "Add probe to obligations controller"

---

app/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/models/eis/subscription/IndividualDetails.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/models/eis/subscriptionDisplay/ChangeOfCircumstanceDetails.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/models/eis/subscriptionDisplay/SubscriptionDisplayResponse.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/ChangeGroupLeadController.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/models/cache/UserAnswers.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/models/cache/gettables/changeGroupLead/ChooseNewGroupLeadGettable.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/models/cache/gettables/changeGroupLead/MainContactJobTitleGettable.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/models/cache/gettables/changeGroupLead/MainContactNameGettable.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/models/cache/gettables/changeGroupLead/NewGroupLeadEnterContactAddressGettable.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/services/ChangeGroupLeadService.scala
conf/app.routes
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/base/it/FakeAuthenticator.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/controllers/ChangeGroupLeadControllerSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/controllers/ReturnsControllerSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/services/ChangeGroupLeadServiceSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/util/Settable.scala

Endpoint to Update group lead from useranswers

---

app/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/ChangeGroupLeadController.scala
it/ChangeGroupLeadItSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/controllers/ChangeGroupLeadControllerSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/models/SubscriptionTestData.scala

clean userAnswer on successful request

---

app/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/SubscriptionsConnector.scala
conf/app.routes
it/PPTFinancialsItSpec.scala
it/PPTObligationsISpec.scala
it/returns/AmendReturnsItSpec.scala
it/returns/ReturnsItSpec.scala
it/support/ObligationSpecHelper.scala
it/support/ReturnWireMockServerSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/base/AuthTestSupport.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/helpers/FinancialTransactionHelper.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/services/ChangeGroupLeadServiceSpec.scala

Pptp 2558 change to proper rest operation

---

app/uk/gov/hmrc/plasticpackagingtaxreturns/config/AppConfig.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/ObligationsDataConnector.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/models/des/enterprise/ObligationDataResponse.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/ObligationsDataConnectorSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/models/PPTObligationDetailsSpec.scala

removed adjusted date as EIS date was fixed

---

app/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/models/eis/returns/ReturnsSubmissionRequest.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/models/cache/gettables/returns/AnotherBusinessExportWeightGattable.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/models/cache/gettables/returns/ExportedByAnotherBusinessPlasticPackagingWeightGettable.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/models/returns/ReturnValues.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/services/PPTCalculationService.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/services/PPTFinancialsService.scala
it/returns/AmendReturnsItSpec.scala
it/returns/CalculationsItControllerSpec.scala
it/returns/ReturnsItSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/models/eis/returns/ReturnsSubmissionRequestSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/controllers/CalculationsControllerSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/controllers/ReturnsControllerSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/models/returns/ReturnValuesSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/services/PPTCalculationServiceSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/support/AmendTestHelper.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/support/ReturnTestHelper.scala

Add exported by another business

---

app/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/CalculationsController.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/ReturnsController.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/models/returns/ReturnValues.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/services/PPTCalculationService.scala
it/returns/AmendReturnsItSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/models/eis/returns/ReturnsSubmissionRequestSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/controllers/ReturnsControllerSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/services/PPTCalculationServiceSpec.scala

add date to return values

---

app/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/ReturnsController.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/models/cache/gettables/amends/AmendExportedByAnotherBusinessPlasticPackagingGettable.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/models/returns/ReturnValues.scala
it/returns/CalculationsItControllerSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/controllers/CalculationsControllerSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/controllers/ReturnsControllerSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/models/returns/ReturnValuesSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/support/AmendTestHelper.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/support/ReturnTestHelper.scala

added exported by another business for amend

---

app/uk/gov/hmrc/plasticpackagingtaxreturns/models/cache/gettables/changeGroupLead/ChooseNewGroupLeadGettable.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/services/ChangeGroupLeadService.scala
it/ChangeGroupLeadItSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/services/ChangeGroupLeadServiceSpec.scala

Pptp 2756 - added crn into Member for CGL

---

app/uk/gov/hmrc/plasticpackagingtaxreturns/models/returns/ReturnValues.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/models/returns/ReturnValuesSpec.scala

return zero if exportedByAnotherBusiness is missing: To

---

app/uk/gov/hmrc/plasticpackagingtaxreturns/config/AppConfig.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/CalculationsController.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/ReturnsController.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/models/calculations/Calculations.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/models/returns/ReturnValues.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/services/PPTCalculationService.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/services/TaxRateService.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/services/WeightToPoundsConversionService.scala
it/returns/CalculationsISpec.scala
it/returns/ReturnsISpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/models/eis/returns/ReturnsSubmissionRequestSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/controllers/CalculationsControllerSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/controllers/ReturnsControllerSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/services/PPTCalculationServiceSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/services/TaxRateServiceSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/services/WeightToPoundsConversionServiceSpec.scala

PPTP- 2761 - pass tax rate to frontend for content

---

app/uk/gov/hmrc/plasticpackagingtaxreturns/services/WeightToPoundsConversionService.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/services/WeightToPoundsConversionServiceSpec.scala

Safe assumption for Credits until 1st July 2023

---

app/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/AvailableCreditDateRangesController.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/services/AvailableCreditDateRangesService.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/controllers/AvailableCreditDateRangesControllerSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/services/AvailableCreditDateRangeServiceSpec.scala

available years to use obligation toDate

---

app/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/CacheController.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/models/returns/CreditRangeOption.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/services/UserAnswersCleaner.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/controllers/CacheControllerSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/services/UserAnswersCleanerSpec.scala

Safe deploy

---

app/uk/gov/hmrc/plasticpackagingtaxreturns/models/UserAnswers.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/services/UserAnswersCleaner.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/models/UserAnswersSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/services/UserAnswersCleanerSpec.scala

Safe remove

---

app/uk/gov/hmrc/plasticpackagingtaxreturns/services/UserAnswersCleaner.scala
it/CacheItSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/services/UserAnswersCleanerSpec.scala

Adding from date to credit

---

app/uk/gov/hmrc/plasticpackagingtaxreturns/services/UserAnswersCleaner.scala
it/CacheItSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/services/UserAnswersCleanerSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/support/ReturnTestHelper.scala

Add credit available date

---

app/uk/gov/hmrc/plasticpackagingtaxreturns/models/SingleYearClaim.scala
app/uk/gov/hmrc/plasticpackagingtaxreturns/services/UserAnswersCleaner.scala
it/CacheItSpec.scala
it/returns/credits/ExportCreditBalanceControllerItSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/services/CreditsCalculationServiceSpec.scala
test/uk/gov/hmrc/plasticpackagingtaxreturns/services/UserAnswersCleanerSpec.scala

rename endDate to toDate
